/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libndkqsp_jni_NDKLib */

#ifndef _Included_org_libndkqsp_jni_NDKLib
#define _Included_org_libndkqsp_jni_NDKLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libndkqsp_jni_NDKLib_init
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPDeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libndkqsp_jni_NDKLib_terminate
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPIsInCallBack
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPIsInCallBack
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPEnableDebugMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_libndkqsp_jni_NDKLib_enableDebugMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetCurStateData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libndkqsp_jni_NDKLib_getCurStateData
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetCompiledDateTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_getCompiledDateTime
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetFullRefreshCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libndkqsp_jni_NDKLib_getFullRefreshCount
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetQstFullPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_getQstFullPath
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetCurLoc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_getCurLoc
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetExprValue
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libndkqsp_jni_NDKLib_getExprValue
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetMainDesc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_getMainDesc
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPIsMainDescChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_isMainDescChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetVarsDesc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_getVarsDesc
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPIsVarsDescChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_isVarsDescChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetVarValuesCount
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libndkqsp_jni_NDKLib_getVarValuesCount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetVarValues
 * Signature: (Ljava/lang/String;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libndkqsp_jni_NDKLib_getVarValues
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetMaxVarsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libndkqsp_jni_NDKLib_getMaxVarsCount
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetVarNameByIndex
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libndkqsp_jni_NDKLib_getVarNameByIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPSetInputStrText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_libndkqsp_jni_NDKLib_setInputStrText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetActionsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetActionsCount
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetActionData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_libndkqsp_jni_NDKLib_getActionData
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPExecuteSelActionCode
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_executeSelActionCode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPSetSelActionIndex
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_setSelActionIndex
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetSelActionIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetSelActionIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPIsActionsChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPIsActionsChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetObjectData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_libndkqsp_jni_NDKLib_getObjectData
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetObjectsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetObjectsCount
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPSetSelObjectIndex
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_setSelObjectIndex
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetSelObjectIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetSelObjectIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPIsObjectsChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPIsObjectsChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPExecString
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_execString
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPExecLocationCode
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPExecLocationCode
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPExecCounter
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_execCounter
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPExecUserInput
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_execUserInput
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetLastErrorData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libndkqsp_jni_NDKLib_getLastErrorData
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetErrorDesc
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_getErrorDesc
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPLoadGameWorldFromData
 * Signature: ([BLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_loadGameWorldFromData
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPSaveGameAsData
 * Signature: (Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_libndkqsp_jni_NDKLib_saveGameAsData__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPOpenSavedGame
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPOpenSavedGame
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPOpenSavedGameFromData
 * Signature: ([BZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_openSavedGameFromData
  (JNIEnv *, jobject, jbyteArray, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPRestartGame
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_restartGame
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPSelectMenuItem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libndkqsp_jni_NDKLib_selectMenuItem
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
